# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8973433047eddaada0c289dc7d8be87f"
name = "GWL Reviews"
application_url = "https://reviews-bundles-production.up.railway.app"
embedded = true
handle = "gwl-reviews"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files,read_files"

[auth]
redirect_urls = [
  "https://reviews-bundles-production.up.railway.app/app/auth/callback",
  "https://reviews-bundles-production.up.railway.app/app/auth/shopify/callback",
  "https://reviews-bundles-production.up.railway.app/api/auth/callback",
  "https://reviews-bundles-production.up.railway.app/auth/callback",
  "https://reviews-bundles-production.up.railway.app/auth/shopify/callback"
]

[app_proxy]
url = "https://reviews-bundles-production.up.railway.app"
subpath = "productreview"
prefix = "apps"

[pos]
embedded = false
